export const USER_SIGNEDIN = 'USER_SIGNEDIN'
export const USER_SIGNEDIN_RESET = 'USER_SIGNEDIN_RESET'

export const USER_SIGNEDUP = 'USER_SIGNEDUP'
export const USER_SIGNEDUP_RESET = 'USER_SIGNEDUP_RESET'

export const PLACE_LIST_ADDED_PLACE = 'PLACE_LIST_ADDED_PLACE'
export const PLACE_LIST_ADDED_PLACE_REMOVE = 'PLACE_LIST_ADDED_PLACE_REMOVE'

export const PLACE_DETAIL_EDITED_PLACE = 'PLACE_DETAIL_EDITED_PLACE'
export const PLACE_DETAIL_EDITED_PLACE_REMOVE = 'PLACE_DETAIL_EDITED_PLACE_REMOVE'
