export const PLACE_LIST_REQUEST = 'PLACE_LIST_REQUEST'
export const PLACE_LIST_SUCCESS = 'PLACE_LIST_SUCCESS'
export const PLACE_LIST_FAIL = 'PLACE_LIST_FAIL'
export const PLACE_LIST_ADDED_PLACE = 'PLACE_LIST_ADDED_PLACE'
export const PLACE_LIST_ADDED_PLACE_REMOVE = 'PLACE_LIST_ADDED_PLACE_REMOVE'

export const PLACE_DETAIL_REQUEST = 'PLACE_DETAIL_REQUEST'
export const PLACE_DETAIL_SUCCESS = 'PLACE_DETAIL_SUCCESS'
export const PLACE_DETAIL_FAIL = 'PLACE_DETAIL_FAIL'
export const PLACE_DETAIL_EDITED_PLACE = 'PLACE_DETAIL_EDITED_PLACE'
export const PLACE_DETAIL_EDITED_PLACE_REMOVE = 'PLACE_DETAIL_EDITED_PLACE_REMOVE'



export const PLACE_CREATE_REQUEST = 'PLACE_CREATE_REQUEST'
export const PLACE_CREATE_SUCCESS = 'PLACE_CREATE_SUCCESS'
export const PLACE_CREATE_FAIL = 'PLACE_CREATE_FAIL'
export const PLACE_CREATE_RESET = 'PLACE_CREATE_RESET'

export const PLACE_EDIT_REQUEST = 'PLACE_EDIT_REQUEST'
export const PLACE_EDIT_SUCCESS = 'PLACE_EDIT_SUCCESS'
export const PLACE_EDIT_FAIL = 'PLACE_EDIT_FAIL'
export const PLACE_EDIT_RESET = 'PLACE_EDIT_RESET'
