export const PLACE_LIST_REQUEST = 'PLACE_LIST_REQUEST'
export const PLACE_LIST_SUCCESS = 'PLACE_LIST_SUCCESS'
export const PLACE_LIST_FAIL = 'PLACE_LIST_FAIL'

export const PLACE_DETAIL_REQUEST = 'PLACE_DETAIL_REQUEST'
export const PLACE_DETAIL_SUCCESS = 'PLACE_DETAIL_SUCCESS'
export const PLACE_DETAIL_FAIL = 'PLACE_DETAIL_FAIL'



export const PLACE_CREATE_REQUEST = 'PLACE_CREATE_REQUEST'
export const PLACE_CREATE_SUCCESS = 'PLACE_CREATE_SUCCESS'
export const PLACE_CREATE_FAIL = 'PLACE_CREATE_FAIL'
export const PLACE_CREATE_RESET = 'PLACE_CREATE_RESET'

export const PLACE_EDIT_REQUEST = 'PLACE_EDIT_REQUEST'
export const PLACE_EDIT_SUCCESS = 'PLACE_EDIT_SUCCESS'
export const PLACE_EDIT_FAIL = 'PLACE_EDIT_FAIL'
export const PLACE_EDIT_RESET = 'PLACE_EDIT_RESET'

export const PLACE_REVIEW_ADD_REQUEST = 'PLACE_REVIEW_ADD_REQUEST'
export const PLACE_REVIEW_ADD_SUCCESS = 'PLACE_REVIEW_ADD_SUCCESS'
export const PLACE_REVIEW_ADD_FAIL = 'PLACE_REVIEW_ADD_FAIL'


export const PLACE_LIKE_REQUEST = 'PLACE_LIKE_REQUEST'
export const PLACE_LIKE_FAIL = 'PLACE_LIKE_FAIL'
export const PLACE_LIKE_SUCCESS = 'PLACE_LIKE_SUCCESS'

export const EDIT_REVIEW_REQUEST = 'EDIT_REVIEW_REQUEST'
export const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS'
export const EDIT_REVIEW_FAIL = 'EDIT_REVIEW_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'