export const SEARCH_CHAT_USER_REQUEST = 'SEARCH_CHAT_USER_REQUEST';
export const SEARCH_CHAT_USER_SUCCESS = 'SEARCH_CHAT_USER_SUCCESS';
export const SEARCH_CHAT_USER_FAIL = 'SEARCH_CHAT_USER_FAIL';

export const ALL_CHATS_REQUEST = 'ALL_CHATS_REQUEST';
export const ALL_CHATS_SUCCESS = 'ALL_CHATS_SUCCESS';
export const ALL_CHATS_FAIL = 'ALL_CHATS_FAIL';
