export const TAG_REQUEST = 'TAG_REQUEST';
export const TAG_SUCCESS = 'TAG_SUCCESS';
export const TAG_FAIL = 'TAG_FAIL';

export const TAG_CAMPGROUND_REQUEST = 'TAG_CAMPGROUND_REQUEST';
export const TAG_CAMPGROUND_SUCCESS = 'TAG_CAMPGROUND_SUCCESS';
export const TAG_CAMPGROUND_FAIL = 'TAG_CAMPGROUND_FAIL';
