export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNIN_RESET = 'USER_SIGNIN_RESET'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET'

export const USER_STATUS_REQUEST = 'USER_STATUS_REQUEST'
export const USER_STATUS_SUCCESS = 'USER_STATUS_SUCCESS'
export const USER_STATUS_FAIL = 'USER_STATUS_FAIL'

export const USER_SIGNOUT_REQUEST = 'USER_SIGNOUT_REQUEST'
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS'
export const USER_SIGNOUT_FAIL = 'USER_SIGNOUT_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_GOOGLE_REQUEST = 'USER_GOOGLE_REQUEST'
export const USER_GOOGLE_SUCCESS = 'USER_GOOGLE_SUCCESS'
export const USER_GOOGLE_FAIL = 'USER_GOOGLE_FAIL'

export const USER_FACEBOOK_REQUEST = 'USER_FACEBOOK_REQUEST'
export const USER_FACEBOOK_SUCCESS = 'USER_FACEBOOK_SUCCESS'
export const USER_FACEBOOK_FAIL = 'USER_FACEBOOK_FAIL'


export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST'
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS'
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL'

export const USER_FOLLOW_STATUS_REQUEST = 'USER_FOLLOW_STATUS_REQUEST'
export const USER_FOLLOW_STATUS_SUCCESS = 'USER_FOLLOW_STATUS_SUCCESS'
export const USER_FOLLOW_STATUS_FAIL = 'USER_FOLLOW_STATUS_FAIL'

export const USER_MY_PROFILE_REQUEST = 'USER_MY_PROFILE_REQUEST'
export const USER_MY_PROFILE_SUCCESS = 'USER_MY_PROFILE_SUCCESS'
export const USER_MY_PROFILE_FAIL = 'USER_MY_PROFILE_FAIL'

export const USER_FACEBOOK_LINK_REQUEST = 'USER_FACEBOOK_LINK_REQUEST'
export const USER_FACEBOOK_LINK_SUCCESS = 'USER_FACEBOOK_LINK_SUCCESS'
export const USER_FACEBOOK_LINK_FAIL = 'USER_FACEBOOK_LINK_FAIL'

export const USER_FACEBOOK_UNLINK_REQUEST = 'USER_FACEBOOK_UNLINK_REQUEST'
export const USER_FACEBOOK_UNLINK_SUCCESS = 'USER_FACEBOOK_UNLINK_SUCCESS'
export const USER_FACEBOOK_UNLINK_FAIL = 'USER_FACEBOOK_UNLINK_FAIL'

export const USER_GOOGLE_LINK_REQUEST = 'USER_GOOGLE_LINK_REQUEST'
export const USER_GOOGLE_LINK_SUCCESS = 'USER_GOOGLE_LINK_SUCCESS'
export const USER_GOOGLE_LINK_FAIL = 'USER_GOOGLE_LINK_FAIL'

export const USER_GOOGLE_UNLINK_REQUEST = 'USER_GOOGLE_UNLINK_REQUEST'
export const USER_GOOGLE_UNLINK_SUCCESS = 'USER_GOOGLE_UNLINK_SUCCESS'
export const USER_GOOGLE_UNLINK_FAIL = 'USER_GOOGLE_UNLINK_FAIL'
