export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNIN_RESET = 'USER_SIGNIN_RESET'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET'

export const USER_STATUS_REQUEST = 'USER_STATUS_REQUEST'
export const USER_STATUS_SUCCESS = 'USER_STATUS_SUCCESS'
export const USER_STATUS_FAIL = 'USER_STATUS_FAIL'

export const USER_SIGNOUT_REQUEST = 'USER_SIGNOUT_REQUEST'
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS'
export const USER_SIGNOUT_FAIL = 'USER_SIGNOUT_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_GOOGLE_REQUEST = 'USER_GOOGLE_REQUEST'
export const USER_GOOGLE_SUCCESS = 'USER_GOOGLE_SUCCESS'
export const USER_GOOGLE_FAIL = 'USER_GOOGLE_FAIL'